### ISSUE TITLE
version not bumping

### ISSUE THREAD

**Issue by AndrewTriesToCode** [versionize/versionize#1]
Hi, nice project.

I'm finding that the version will not auto-bump. I must use `-r` to get the correct version otherwise it says changing from 2.0.0 to 2.0.0 then hits an exception trying to create the tag because one already exists. I would expect it to go to 2.0.1 due to a `fix:` commit. It correctly creates the changeling with the fix listed. I also tried with `feat` and `BREAKING CHANGE:` and the changelog is updated corrected but the version is unchanged. Thanks.

**Comment by achandlerwhite** [comment]
Thanks for the reply. I actually have my current released tagged as v2.0.0
in an earlier commit. Should it be recognizing that?

**Comment by saintedlama** [comment]
Should recognize tags with a v version prefix. Is that project open source and on github so I could check if this is an issue with versionize

**Comment by achandlerwhite** [comment]
Hi, yes I created a branch that will show this:
https://github.com/achandlerwhite/Finbuckle.MultiTenant/tree/test/versionize

It is currently tagged v2.0.1 2 commits back and one of the commits is a "fix" (the projects in the /src folder). Running versionize attests to bump from "2.0.1 to 2.0.1". I would expect is to bump to 2.0.2.

Also I normally keep one version property in a Directory.Build.Props file which msbuild includes in each project. I noticed Versionize doesn't recognize it there so I moved the version tag to each project individually in src. Maybe a future enhancement idea to support a setup like that?

**Comment by achandlerwhite** [comment]
Thanks for taking a look and for this project.

 When I look at that branch I see a v2.0.1 version as the last git version tag and so I expected Versionize to bump to v2.0.2 . But are you saying that Versionize doesn't see the v2.0.1 tag and is only seeing the v2.0.0 tag?

**Comment by cabauman** [comment]
Closing this issue based on age. Feel free to open a new issue if you encounter more trouble.
