### ISSUE TITLE
[FR] Add support of --allow-different-versions option

### ISSUE THREAD

**Issue by goblinmaks** [versionize/versionize#107]
Add support of --allow-different-versions option for case when folder contains lot of projects with different versions.

**Comment by cabauman** [comment]
Check out the commit that adds [monorepo support](https://github.com/versionize/versionize/commit/37a5cf96984dfe52cbf0b0a52889e6015bb405c7#diff-c41a3273b7c18af52bde8f810fbc301e8d71b357a6cf8d547c54dd479e4512f6), which allows different project versions. You can find usage examples in the integration tests he added. I hope this helps!
