### ISSUE TITLE
set a configuration file .versionrc like "standard-version" exist in node.js

### ISSUE THREAD

**Issue by Notim** [versionize/versionize#11]
I don't know if you know a lib called standard-version in node.js, I like it a lot, but it works only in javascript projects with node.

I made a task in my pipeline that it generates the tag and the changelog and already pulls the branch I'm working on.
it made my life too easy.

your lib is perfect also for those who have dotnet projects.

however I missed something that was in the lib in node.js that I think is not difficult to implement in your lib.

A configuration file like .versionrc.json, where we can place the url to see the commit on provider by sha hash, comparison between versions, title of the changelog, add other types of sections (chore, refactor, docs, build, test, etc..).

**Comment by saintedlama** [comment]
Would ❤️ to implement such a mechanism - have a "first draft" how it could look like and which are the most important features to you?

**Comment by saintedlama** [comment]
Implemented in master, should be released shortly
