### ISSUE TITLE
AzDo/GitHub/GitLab shouldn't overwrite linkTemplates from .versionize

### ISSUE THREAD

**Issue by alasdair-cooper** [versionize/versionize#111]
The `LinkBuilderFactory` overwrites `linkTemplates` (from `.versionize`) if the current repo has a remote that has a matching link builder.

Provided link templates should have the highest precedence.

This would also let people be able to fix issues like #105 without having to do a PR.

**Comment by cabauman** [comment]
Good point. At first glance, this looks simple to do. I'll check it out soon.
