### ISSUE TITLE
.versionize JSON folder directory

### ISSUE THREAD

**Issue by raz789** [versionize/versionize#122]
Is there currently any way to define the configuration file directory? 
This would be useful when I have a shared configuration across multiple repositories for consistency in changelog and versioning.

Currently I'm just copying the configuration file to the working directory, then making sure it's ignored in the gitignore.

**Comment by raz789** [comment]
https://github.com/versionize/versionize/pull/123

I gave it a go here. But it may not be up to the expected code standards.

**Comment by cabauman** [comment]
Yeah, this use-case seems worthwhile! I'll give it a review soon.

**Comment by cabauman** [comment]
Merged! Thanks for the contribution.

**Comment by raz789** [comment]
Just got the email, cheers for getting this in!
