### ISSUE TITLE
Add option to versionize Unity projects

### ISSUE THREAD

**Issue by WeirdBeardDev** [versionize/versionize#132]
Unity autogenerates the csproj files, any changes are quickly overwritten. Unity instead saves the version info in the `ProjectSettings/ProjectSettings.asset` file as `bundleVersion`.  Could an option be added that considers the alternate location and format (asset files are YAML) for versionizing Unity projects?

**Comment by cabauman** [comment]
Possibly. I work a lot in Unity, but usually handle versioning with a GitHub Action without Versionize. I'll look into it.

**Comment by cabauman** [comment]
I'm refactoring in V2, which will simplify adding this kind of feature.

**Comment by cabauman** [comment]
resolved by #150
