### ISSUE TITLE
Feature request: Add in .versionize "outputChangelog" (or similar) to define where the CHANGELOG is read/write

### ISSUE THREAD

**Issue by RemiCELLARD** [versionize/versionize#138]
Hi,

Thanks for this library. It's pretty nice to have a automatic resume all the work that we've done on version.
However, i publish my changelog in an other folder called "docs". No parameter exists to change CHANGELOG file location.
Is it possible to add this parameter to the `.versionize` file in the `ProjectOptions.cs` ?

Example - Here's a sample of my folder structure : 

MyRepository
┣📂 .github
┣📂 docs
┃┗━ 📖 CHANGELOG.md
┣📂 src
┃ ┣📂 Core
┃ ┃ ┣━━ 📦 MyRepository.App
┃ ┃ ┗━━ 📦 MyRepository.Domain
┃ ┣📂 Presentation
┃ ┃ ┗ 📂 Front
┃ ┃ .....┗━━ 📦 MyRepository.FrontApp
┃ ┣📂 Tests
┃ ┣📜 MyRepository.sln
┃ ┣📜 nuget.config
[ ...... ]

┣━ 📖 README.md
┣━ 🗎 .gitignore
[.......]

**Comment by cabauman** [comment]
Yeah, we can add this.

**Comment by RemiCELLARD** [comment]
Ready for Versionize v2 #135
