### ISSUE TITLE
 Feature request: Add in .versionize "firstParentOnlyCommit" (or similar) to have only the first parent of each commit in branch

### ISSUE THREAD

**Issue by RemiCELLARD** [versionize/versionize#139]
Hi,

Thanks for this library. It's pretty nice to have a automatic resume all the work that we've done on version.
I have a project where I regularly perform commits and pull requests on a local azure devops.
However, when I try to generate the changelog, it outputs all the commits I've made on the branches used in the pull requests.

I'd like to know if we can add an option to include only parent commits in the changelog.

I've seen that in the library `libgit2sharp`, you can add a filter to display only the parent commits of a branch.
See : https://github.com/libgit2/libgit2sharp/blob/5085a0c6173cdb2a3fde205330b327a8eb0a26c4/LibGit2Sharp/CommitFilter.cs#L65

Note: I saw that there was a similar topic already open ( #118 )

**Comment by cabauman** [comment]
Would you mind adding an example scenario so I can better visualize the desired input/output? So multiple branches are involved in a single pull request?

**Comment by RemiCELLARD** [comment]
Here's an example

Before (FirstParentOnly = false) :
![image](https://github.com/user-attachments/assets/4491eea7-a39e-438e-89fa-cc65885cd0c1)

After (FirstParentOnly = true) :
![image](https://github.com/user-attachments/assets/1db22de3-741f-42de-aa41-ea415176c944)

**Comment by cabauman** [comment]
Sure, that works.

**Comment by RemiCELLARD** [comment]
Ready for Versionize v2 #135
