### ISSUE TITLE
Changelog path option overwrites CHANGELOG.md if multiple projects point to the same location

### ISSUE THREAD

**Issue by Barsan1** [versionize/versionize#146]
If there's a conflict between two projects with the same changelog path, it should be addressed.
If this is by design, we need to document it clearly, and I'll add this to the documentation. 

Otherwise, we have some options:

1. Display an interactive message to confirm the action with a yes/no prompt.
2. Exit with an error message if two changelog paths point to the same location.

**Comment by cabauman** [comment]
We can go with option 2 to give it the same behavior as other error case scenarios.

**Comment by RemiCELLARD** [comment]
Hi,

Option 2 seems a good choice.
