### ISSUE TITLE
Support for pre-release versions

### ISSUE THREAD

**Issue by maximemauro** [versionize/versionize#23]
Hello there,

Having the possibility to use versionize to create pre-release versions would be great!

https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages

Is it planned in a near future? Thanks!

**Comment by torsten-scholer-healex** [comment]
+1 for this feature request.

**Comment by dd52** [comment]
+1

**Comment by maggusw** [comment]
+1

**Comment by cabauman** [comment]
Now supported in version 1.11.0! #50
