### ISSUE TITLE
Versionize stopped working in Ubuntu 18.04

### ISSUE THREAD

**Issue by lungosta** [versionize/versionize#28]
Versionize stopped working in Ubuntu 18.04, I'm getting the following error when I try to create changelog:

free(): invalid pointer
/home/vsts/work/_temp/513c9359-e347-4729-819c-0b31e4782f8d.sh: line 1:  3328 Aborted

Example command:
/home/vsts/work/versionize -w "health-reimbursement-ms/" -r 0.3.3 --skip-dirty --skip-commit -i

This is happening with 1.6.2,1.6.1 and 1.6.0

**Comment by maximemauro** [comment]
Exact same issue on my side.
We use versionize in a Docker image based on mcr.microsoft.com/dotnet/sdk:5.0 (Debian 10)

**Comment by saintedlama** [comment]
Took a look today and perhaps a `--skip-commit` could help

**Comment by DeltaOffset** [comment]
hey @saintedlama I work with lungosta and we are still having problems running versionize. don't know what happened but we get an error like: "free(): invalid pointer"
when running the command versionize --skip-dirty --skip-commit -i

**Comment by lungosta** [comment]
@saintedlama have you been able to have a look at this?

**Comment by msallin** [comment]
There was a change in the newest .NET 5 SDK which causes an error with marshalling in the gitlib2. This is fixed with a preview.

https://github.com/libgit2/libgit2sharp/pull/1890

**Comment by saintedlama** [comment]
Had a look at that issue and the root of all evil is buried somewhere in libgit2sharp. Tried to downgrade/upgrade but no luck yet.

**Comment by msallin** [comment]
"0.27.0-preview-0102 includes the fix."
https://github.com/libgit2/libgit2sharp/issues/1885

**Comment by DeltaOffset** [comment]
we did a test on versionize --version 1.5.1 on Ubuntu 18.04 and is working, at least we could use this until its fixed for newer version

**Comment by saintedlama** [comment]
Should be fixed in v1.7.0

**Comment by cabauman** [comment]
Closing this issue since there haven't been any more reports. Feel free to open a new issue if you find otherwise.
