### ISSUE TITLE
Author name Issue

### ISSUE THREAD

**Issue by shabirjan** [versionize/versionize#4]
Hi
While running the Versionize Command in Azure DevOps release pipeline using Command Prompt, I am getting this error.
`√ bumping version from 1.0.1 to 1.0.2 in projects √ updated CHANGELOG.md Unhandled Exception: System.ArgumentNullException: Value cannot be null. Parameter name: author at LibGit2Sharp.ObjectDatabase.CreateCommit(Signature author, Signature committer, String message, Tree tree, IEnumerable`1 parents, Boolean prettifyMessage, Nullable`1 commentChar) at LibGit2Sharp.Repository.Commit(String message, Signature author, Signature committer, CommitOptions options) at LibGit2Sharp.RepositoryExtensions.Commit(IRepository repository, String message, Signature author, Signature committer) at Versionize.WorkingCopy.Versionize(Boolean dryrun, Boolean skipDirtyCheck, Boolean skipCommit, String releaseVersion) in C:\p\github\versionize\Versionize\WorkingCopy.cs:line 116 at Versionize.Program.<>c__DisplayClass0_0.<Main>b__0() in C:\p\github\versionize\Versionize\Program.cs:line 34 at Versionize.Program.Main(String[] args) in C:\p\github\versionize\Versionize\Program.cs:line 45`

But When I run the Versionize Command Locally, i am not getting any error.

**Comment by saberone** [comment]
For anyone that bumps in to this issue, when using Azure DevOps
I have this task in our build pipeline.

```
- task: CmdLine@2
    displayName: "Set git user"
    inputs:
      script: |
        git config --global user.email "devops@ops.dev"
        git config --global user.name "Azure DevOps"
```

**Comment by cabauman** [comment]
Thanks for the example. We have also [added a warning](https://github.com/versionize/versionize/commit/5782999c4967fd408c44ced1bffad697b22ba117) when this case is encountered, so it should be more obvious now.
