### ISSUE TITLE
Color functionality broken on Windows

### ISSUE THREAD

**Issue by cabauman** [versionize/versionize#46]
**OS:** Windows 11 Pro
**OS Build:** 22000.434

Color functionality isn't working for me, and based on browsing the [Colorful.Console](https://github.com/tomakita/Colorful.Console) repository, it seems it might be related to newer Windows versions. Unfortunately, it looks like activity in the Colorful.Console repo has slowed down a lot these days. I'd be happy to post an issue in that repo, but thought I'd bring it up here in case you wanted to start considering alternatives or workarounds.

I cloned the Colorful.Console repo and ran an example with the following results:

![Screenshot 2022-02-01 123719](https://user-images.githubusercontent.com/6819362/151911229-bd63a2ad-4516-47be-92d9-59767b6355b7.jpg)

Crazy stuff going on there 😅

**EDIT**

It's currently calling [GetConsoleColorNative](https://github.com/tomakita/Colorful.Console/blob/master/src/Colorful.Console/ColorManager.cs#L85). When I altered that path to do `color.ToNearestConsoleColor()` instead, it works fine:

![Screenshot 2022-02-01 132328](https://user-images.githubusercontent.com/6819362/151912570-cd95c561-2d4c-464f-b958-b878b65fb752.jpg)

Might be worth just dropping the library and doing a simple extension, since you're not using the advanced features:

```csharp
private static void WriteInColor<T>(Action<T> action, T target, ConsoleColor color)
{
    var oldColor = System.Console.ForegroundColor;
    System.Console.ForegroundColor = color;
    action.Invoke(target);
    System.Console.ForegroundColor = oldColor;
}
```

**Comment by saintedlama** [comment]
What about moving to https://github.com/spectreconsole/spectre.console ? Looks well maintained
