### ISSUE TITLE
Versionize fails with repository dirty with untracked files present while git reports repo is not dirty

### ISSUE THREAD

**Issue by jmartens** [versionize/versionize#60]
Versionize fails when there are files that are not tracked in the folder of the repository mentioning the repository is dirty. Git does not describe this as dirty as it is perfectly fine to have untracked files in the same folder.

I would not have expected this to be preventing versionize to run and if it was a problem I would have expected a message stating that there are untracked files, not the repo being dirty since git's dirty has a different meaning.

**Comment by saintedlama** [comment]
Investigating that use case currently, it's feasible to be fixed but might lead to some unintended behavior. Before digging deeper, what's the use case for excluding the untracked files from git status check to determine if a repo is dirty?

**Comment by cn-ml** [comment]
It would be nice to see which files are not clean (i.e. prevent the tool from running). I just tried to configure my CI with versionize and failed because of this error. Currently i am running a `git reset --hard` at the start of my ci script to clean the environment.

**Comment by smitchamwork** [comment]
As a debug step I added a 'git diff' into my build script on the line prior to versionize, however, something built in would be nice.  In my case it was script files that weren't set as executable in the index that were automatically getting converted by Github actions to executable.

**Comment by cabauman** [comment]
[Versionize uses](https://github.com/versionize/versionize/blob/85daaffd8f32728029fa77030cc98f05b9bda0c9/Versionize/WorkingCopy.cs#L54) LibGit2Sharp's default definition of "dirty".

```csharp
var isDirty = repo.RetrieveStatus(new StatusOptions()).IsDirty;
```

where `StatusOptions.IncludeUntracked` is [set to true by default](https://github.com/libgit2/libgit2sharp/blob/5085a0c6173cdb2a3fde205330b327a8eb0a26c4/LibGit2Sharp/StatusOptions.cs#L39).

So, we can either set `IncludeUntracked` to false or attempt to list the file names in the error message. Which do you guys prefer?
