### ISSUE TITLE
Add option to aggregate pre-release changes

### ISSUE THREAD

**Issue by cabauman** [versionize/versionize#74]
This was requested in standard-version a long time ago but still hasn't made it in. I think it's a very common use case.

Currently, the following sequence of commands
```
versionize --pre-release alpha
versionize --pre-release alpha
versionize
```

would generate a changelog resembling
```
v1.0.0-alpha.0
- featA
v1.0.0-alpha.1
- featB
v1.0.0
```

But I propose something like
```
versionize --pre-release alpha
versionize --pre-release alpha
versionize --aggregate-pre-releases
```

to get output like
```
v1.0.0-alpha.0
- featA
v1.0.0-alpha.1
- featB
v1.0.0
- featA
- featB
```

Can also be used together with the pre-release flag
```
versionize --pre-release alpha --aggregate-pre-releases
```

**Related standard-version tickets**

https://github.com/conventional-changelog/standard-version/issues/203
https://github.com/conventional-changelog/standard-version/issues/827

**Comment by jonahbohlmann** [comment]
Hello,

I think is a really important feature. Can you please try to implement this? 

Maybe you can describe how you would implement this and I can try to help with a pull-request?

Thanks,
Jonah
