### ISSUE TITLE
[BUG] false Bump version statement 

### ISSUE THREAD

**Issue by Abudinka** [versionize/versionize#78]
the commandline respond after executing versionize updates the project version upon writing the proj file thus stating something like this 
```
Discovered 1 versionable projects
  * C:\xxx.csproj
V bumping version from 1.2.0 to 1.2.0 in projects
V updated CHANGELOG.md
V committed changes in projects and CHANGELOG.md
V tagged release as 1.2.0

i Run `git push --follow-tags origin master` to push all changes including tags
```
the line bumping version should say something like `1.1.4 to 1.2.0 ` 

this is probaply fixed by moveing the message in workingcopy.cs from line 150 to line 138 

alternatively one could have a look why the call of` Project.WriteVersion` (project.cs line 58) actually alters the result of the `Project.Version` property

im currently making some adjustments to the software to meet my requirements and im probably opening some issue for further discussion on the issues (Spoiler: delphi and numeric versioning support)

**Comment by saintedlama** [comment]
Have some commits example to reproduce the issue? Thanks for filing an issue and PRs are welcome.

**Comment by Abudinka** [comment]
I'am  rather new to github so I properbly will make a lot of mistakes, but just to verify here is a screenshot, 

as I said a fix is rather simple but does not tackle the root cause. I assume the way to go forward would be

1. fork the project
2. fix the bug
3. commit it to my repo 
4. start pull request

Am I missing something 


![version bump commit](https://user-images.githubusercontent.com/58987278/179683651-a568db46-e34d-48c8-8a84-e9f4b5dfdc05.png)
