### ISSUE TITLE
Versionize are making changes when no commits

### ISSUE THREAD

**Issue by skoniam** [versionize/versionize#84]
When no new commits since last version Versionize make a section in CHABGELOG.md and changing PATCH version.
In my opinion when no new commits since last version Versionize should exit with message: 
```output
No commits since last version ({projects.Version})
```

**Comment by cabauman** [comment]
Does the `--ignore-insignificant-commits` option fit your use case?

> Do not bump the version if no significant commits (fix, feat or BREAKING) are found.

This exits early with the message: _$"Version was not affected by commits since last release ({projects.Version})"_

**Comment by cabauman** [comment]
I'll go ahead and close this issue, but if my response above isn't sufficient for your use case, feel free to reopen.
