### ISSUE TITLE
Bump project with workDir does not work as expected

### ISSUE THREAD

**Issue by florimm** [versionize/versionize#89]
I created a sample repo (https://github.com/florimm/SemanticRelease) that have two projects (in different folders) and Im trying to update version only for one project but when I run Versionize it updates both (I think it should only one) even if I send parameter for workingDir or even if I run from the subfolder of the project.

Am I doing something wrong ?

**Comment by Tobbe3108** [comment]
I just ran into this problem.
I expected that setting "--workingDir" would limit Versionize to only bump projects in that directory.
This is inconsistent behavior compared to other cli tools.

**Comment by cabauman** [comment]
Fixed by #90
