### ISSUE TITLE
Invalid API key in publish.yml

### ISSUE THREAD

**Issue by Tobbe3108** [versionize/versionize#92]
The api key: `${{secrets.NUGET_API_KEY}}` in [publish.yml](https://github.com/versionize/versionize/blob/89a9c8e136e4e3289ed53422bfb656cc12e777db/.github/workflows/publish.yml) is invalid.
This is preventing new releases from being published to NuGet.
[Publish to Nuget · versionize/versionize@89a9c8e](https://github.com/versionize/versionize/actions/runs/4084848311/jobs/7042049250#step:8:8)

**Comment by cabauman** [comment]
@saintedlama did the nuget key have an expiration or something?

**Comment by saintedlama** [comment]
@cabauman yes, the key expired - just added a new key to make publishing work again
