### ISSUE TITLE
Is there an example of how to use versionize with github/azuredevops action to Auto generate change logs

### ISSUE THREAD

**Issue by swarooprooney** [versionize/versionize#99]
Is there an example of how to use versionize with github/azuredevops action to Auto generate change logs i.e. do we have azure devops or github actions supporting this?

**Comment by cabauman** [comment]
You can see a GitHub Actions example in our [publish workflow](https://github.com/versionize/versionize/blob/master/.github/workflows/publish.yml). I've never used azuredevops though, sorry.
